const types = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_TRANSACTIONS_ERORR: 'FETCH_TRANSACTIONS_ERORR',
  // Global
  GLOBAL_FETCH_START: 'global/FETCH_START',
  GLOBAL_FETCH_FINISH: 'global/FETCH_FINISH',
  GLOBAL_FETCH_ERROR: 'global/FETCH_ERROR',
  IS_MODAL_LOGOUT_OPEN: 'global/IS_MODAL_LOGOUT_OPEN',
  IS_MODAL_LOGOUT_CLOSE: 'global/IS_MODAL_LOGOUT_CLOSE',
  IS_MODAL_DELETE_OPEN: 'global/IS_MODAL_DELETE_OPEN',
  IS_MODAL_DELETE_CLOSE: 'global/IS_MODAL_DELETE_CLOSE',
  OPEN_MODALADDTRANSACTION: 'OPEN_MODALADDTRANSACTION',
  CLOSE_MODALADDTRANSACTION: 'CLOSE_MODALADDTRANSACTION',
};

export default types;
