const types = {
  // Login and Registration
  LOGIN_REQUEST: 'session/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'session/LOGIN_SUCCESS',
  LOGIN_ERROR: 'session/LOGIN_ERROR',
  REGISTER_REQUEST: 'session/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'session/REGISTER_SUCCESS',
  REGISTER_ERROR: 'session/REGISTER_ERROR',
  REFRESH_CURRENT_REQUEST: 'session/REFRESH_CURRENT_REQUEST',
  REFRESH_CURRENT_SUCCESS: 'session/REFRESH_CURRENT_SUCCESS',
  REFRESH_CURRENT_ERROR: 'session/REFRESH_CURRENT_ERROR',
  // Global
  GLOBAL_FETCH_START: 'global/FETCH_START',
  GLOBAL_FETCH_FINISH: 'global/FETCH_FINISH',
  GLOBAL_FETCH_ERROR: 'global/FETCH_ERROR',
  IS_MODAL_LOGOUT_OPEN: 'global/IS_MODAL_LOGOUT_OPEN',
  IS_MODAL_LOGOUT_CLOSE: 'global/IS_MODAL_LOGOUT_CLOSE',
  IS_MODAL_DELETE_OPEN: 'global/IS_MODAL_DELETE_OPEN',
  IS_MODAL_DELETE_CLOSE: 'global/IS_MODAL_DELETE_CLOSE',
  OPEN_MODALADDTRANSACTION: 'OPEN_MODALADDTRANSACTION',
  CLOSE_MODALADDTRANSACTION: 'CLOSE_MODALADDTRANSACTION',
};

export default types;
